In [2]:
import pandas as pd 
import pymysql 
import pymysql.cursors
import numpy as np
from scipy.stats import chisquare
from scipy import stats
import scipy as sp
import statsmodels.api as sm
from statsmodels.formula.api import ols, logit, glm
import seaborn as sns
import numpy as np
from sklearn.linear_model import LinearRegression
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

from sklearn.neighbors import KNeighborsRegressor

In [3]:
import mglearn
import matplotlib.pyplot as plt

# matplotlib 에서 한글 문제 해결(Window)
from matplotlib import font_manager, rc
font_name = font_manager.FontProperties(fname="c:/Windows/Fonts/malgun.ttf").get_name()
rc('font', family=font_name)

In [21]:
all_product = pd.read_excel('0126_2_score_default.xlsx')
all_product

,product_id,p_cow,p_chicken,p_fish,p_turkey,p_sheep,p_pig,p_duck,p_salmon,p_tuna,p_insect,o_chicken,o_fish
0,1,0.0,4.0,3.0,4.0,0.0,0.0,1.0,0.0,0.0,0.0,0,1
1,2,0.0,4.0,3.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
2,3,0.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
3,4,0.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
4,5,0.0,4.0,3.0,4.0,0.0,0.0,1.0,0.0,0.0,0.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2631,17740,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
2632,17741,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
2633,17742,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
2634,17743,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
2635,17744,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.5,0.0,0.0,0,0

In [23]:
sample

[[9,
  0.0,
  0.36363636363636365,
  0.5,
  0.5714285714285714,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0],
 [285,
  0.0,
  0.36363636363636365,
  0.0,
  0.14285714285714285,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0],
 [418,
  0.14285714285714285,
  0.0,
  0.0,
  0.0,
  0.0,
  0.14285714285714285,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0],
 [565,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.1111111111111111,
  0.3333333333333333,
  0.0,
  0.0],
 [1468,
  0.0,
  0.0,
  0.0,
  0.0,
  0.14285714285714285,
  0.0,
  0.0,
  0.0,
  0.3333333333333333,
  0.0,
  0.0],
 [9311,
  0.0,
  0.0,
  0.16666666666666666,
  0.14285714285714285,
  0.0,
  0.0,
  0.0,
  0.1111111111111111,
  0.0,
  0.0,
  1.0],
 [9627,
  0.0,
  0.09090909090909091,
  0.0,
  0.0,
  0.14285714285714285,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0],
 [15347,
  0.0,
  0.2727272727272727,
  0.0,
  0.0,
  0.0,
  0.14285714285714285,
  0.16666666666666666,
  0.1111111111111111,
  0.0,
  0.0,
  1.0],
 [15590,
  0.14285714285714285,
  0.0,
  0.5,
  0.0,
  0.0,
  0.0,
  0.16666666666666666,
  0.0,
  0.0,
  0.14285714285714285,
  0.0]]

In [26]:
## 정규화
from sklearn.preprocessing import MinMaxScaler, StandardScaler

scaler = MinMaxScaler()
#scaler = StandardScaler
variables = all_product[['p_cow' , 'p_chicken' , 'p_fish' , 'p_turkey' ,'p_pig', 'p_sheep' , 'p_duck' ,'p_salmon' , 'p_tuna'  ,'p_insect', 'o_chicken' , 'o_fish']]
scaled_variables = scaler.fit_transform(variables)
scaled_variables =  scaled_variables.tolist()



product_id_list = all_product['product_id'].tolist()

result = []

for i, data in enumerate(scaled_variables) :
    pre_result = []
    pre_result.append(product_id_list[i])
    for number in range(12) :
        pre_result.append(data[number])
    result.append(pre_result)

sample = []
for data in result :
    if data[0] in [	9	,
	285	,
	418	,
	565	,
	1468	,
	9311	,
	9627	,
	15247	,
	15347	,
	15590	] :
        sample.append(data)
    





column = ['product_id', 'p_cow' , 'p_chicken' , 'p_fish' , 'p_turkey' ,'p_pig', 'p_sheep', 'p_duck' ,'p_salmon' , 'p_tuna'  ,'p_insect', 'o_chicken' , 'o_fish']
scaled_df = pd.DataFrame.from_records( result , columns = column )

#scaled_df.to_excel('scaled_df.xlsx')

In [27]:
# 0. 데이터 불러오기

test_result = pd.read_excel("c:\import\gihosung\s_0124_testresult.xlsx",sheet_name = 'result')
test_result2 = pd.read_excel("c:\import\gihosung\s_0124_testresult.xlsx",sheet_name = 'result2') #빅독제외
scaled_result = pd.read_excel("c:\import\gihosung\s_0124_testresult.xlsx",sheet_name = 'scaled_result')

df = scaled_result

x = df[['p_cow' , 'p_chicken' , 'p_fish' , 'p_turkey' ,'p_pig', 'p_sheep', 'p_duck' ,'p_salmon' , 'p_tuna'  ,'p_insect', 'o_chicken' , 'o_fish']]
y = df[['제리']]
feature_list = ['p_cow' , 'p_chicken' , 'p_fish' , 'p_turkey' ,'p_pig', 'p_sheep' ,  'p_salmon' , 'p_tuna'  ,'p_insect', 'o_chicken' , 'o_fish' ]
######

In [41]:
# 2. 모델 학습 및 결과도출

clf = KNeighborsRegressor(n_neighbors = 1, weights = "distance")
clf.fit(x, y)

pred = clf.predict(scaled_df[[ 'p_cow' , 'p_chicken' , 'p_fish' , 'p_turkey' ,'p_pig', 'p_sheep', 'p_duck' ,'p_salmon' , 'p_tuna'  ,'p_insect', 'o_chicken' , 'o_fish']])
pred
#######
y_pred = list(pred)

df = pd.read_excel("제리.xlsx")
df['knn_score'] = 0

for index,score in enumerate(y_pred) :
    #print(index, score)
    df['knn_score'][index] = score

df
df.to_excel("제리_final_1.xlsx")

C:\Users\지상민\AppData\Local\Temp/ipykernel_19836/466351268.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['knn_score'][index] = score

In [36]:
#회귀

reg = sm.OLS(y, x).fit()
reg.summary()

C:\visual studio\lib\site-packages\scipy\stats\stats.py:1541: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=10
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "
C:\visual studio\lib\site-packages\statsmodels\regression\linear_model.py:1728: RuntimeWarning: divide by zero encountered in true_divide
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)
C:\visual studio\lib\site-packages\statsmodels\regression\linear_model.py:1728: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)
C:\visual studio\lib\site-packages\statsmodels\regression\linear_model.py:1650: RuntimeWarning: divide by zero encountered in double_scalars
  return np.dot(wresid, wresid) / self.df_resid

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                     제리   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                    nan
Method:                 Least Squares   F-statistic:                       nan
Date:                Fri, 28 Jan 2022   Prob (F-statistic):                nan
Time:                        15:55:18   Log-Likelihood:                 276.69
No. Observations:                  10   AIC:                            -533.4
Df Residuals:                       0   BIC:                            -530.4
Df Model:                           9
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
p_cow         75.3377        inf          0        nan         nan         nan
p_chicken    851.4508        inf          0        nan         nan         nan
p_fish       648.1385        inf          0        nan         nan         nan
p_turkey      78.4219        inf          0        nan         nan         nan
p_pig       1355.1677        inf          0        nan         nan         nan
p_sheep     -360.0881        inf         -0        nan         nan         nan
p_duck      -345.2789        inf         -0        nan         nan         nan
p_salmon    1904.3585        inf          0        nan         nan         nan
p_tuna       268.2138        inf          0        nan         nan         nan
p_insect      54.0029        inf          0        nan         nan         nan
o_chicken    347.6786        inf          0        nan         nan         nan
o_fish      -381.5002        inf         -0        nan         nan         nan
==============================================================================
Omnibus:                        0.996   Durbin-Watson:                   0.786
Prob(Omnibus):                  0.608   Jarque-Bera (JB):                0.797
Skew:                          -0.491   Prob(JB):                        0.671
Kurtosis:                       2.027   Cond. No.                         47.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.
"""